### ISSUE TITLE
'Get Started' Button Not Redirecting to Kyrix Site

### ISSUE THREAD

**Issue by soham-basak** [nilotpaul/evolveasdev.com#3]
### The 'Get Started' button in the homepage section [Try out Kyrix] is currently not redirecting to kyrix.evolveasdev.com as expected.

**Expected Behavior:**
When a user clicks on the 'Get Started' button, it should redirect them to kyrix.evolveasdev.com.

**Actual Behavior:**
Clicking the 'Get Started' button does not perform the redirection or navigates to an incorrect link.

**Comment by nilotpaul** [comment]
Fixed
